services:
  - type: web
    name: advanced-attendance-system
    env: python
    runtime: python3.10.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
