services:
  - type: web
    name: advanced-attendance-system
    env: python
    runtime: python3
    buildCommand: |
      python3.10 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: PATH
        value: /opt/python/3.10.11/bin:$PATH
