name: Deploy Face Recognition Attendance System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Add deadsnakes PPA and install system dependencies
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install -y python3.9 python3.9-dev
          sudo apt-get install -y cmake build-essential pkg-config
          sudo apt-get install -y libx11-dev libatlas-base-dev
          sudo apt-get install -y libgtk-3-dev libboost-python-dev
          sudo apt-get install -y libopenblas-dev liblapack-dev
          sudo apt-get install -y python3-dev
          sudo apt-get install -y libsm6 libxext6 libxrender-dev
          sudo apt-get install -y libgl1 libglib2.0-0

      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install cmake --no-cache-dir
          python -m pip install numpy==1.21.0 --no-cache-dir

      - name: Install dlib
        run: |
          git clone https://github.com/davisking/dlib.git
          cd dlib
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cd ..
          python setup.py install

      - name: Install remaining dependencies
        run: |
          pip install face-recognition
          pip install -r requirements.txt

      - name: Create required directories
        run: |
          mkdir -p static/student_photos
          mkdir -p static/attendance_sheets
          mkdir -p static/class_photos
          mkdir -p encodings

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.4'

      - name: Set environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Initialize database
        run: |
          python init_db.py

      - name: Build and check application
        run: |
          python -c "import face_recognition; import cv2; import numpy; print('Dependencies successfully imported')"
