name: Deploy Face Recognition Attendance System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Add deadsnakes PPA and install system dependencies
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install -y python3.9 python3.9-dev
          sudo apt-get install -y cmake build-essential pkg-config
          sudo apt-get install -y libx11-dev libatlas-base-dev
          sudo apt-get install -y libgtk-3-dev libboost-python-dev
          sudo apt-get install -y libopenblas-dev liblapack-dev
          sudo apt-get install -y python3-dev
          sudo apt-get install -y libsm6 libxext6 libxrender-dev
          sudo apt-get install -y libgl1 libglib2.0-0
          sudo apt-get install -y gcc g++ wget make

      - name: Install Python build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install numpy==1.21.0

      - name: Download and install dlib
        run: |
          wget http://dlib.net/files/dlib-19.22.tar.bz2
          tar xvf dlib-19.22.tar.bz2
          cd dlib-19.22
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cd ..
          python setup.py install --no USE_AVX_INSTRUCTIONS

      - name: Install OpenCV separately
        run: |
          pip install opencv-python-headless==4.5.3.56

      - name: Install face recognition
        run: |
          pip install face-recognition-models
          pip install face-recognition

      - name: Install project requirements
        run: |
          pip install -r requirements.txt

      - name: Create required directories
        run: |
          mkdir -p static/student_photos
          mkdir -p static/attendance_sheets
          mkdir -p static/class_photos
          mkdir -p encodings

      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.4'

      - name: Set environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Initialize database
        run: |
          python init_db.py

      - name: Build and check application
        run: |
          python -c "import face_recognition; import cv2; import numpy; print('Dependencies successfully imported')"
